# Etapa 1: Build
FROM node:20-alpine AS builder

# Crear directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json (o yarn.lock)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .



# Etapa 2: Runtime
FROM node:20-alpine AS runner

# Crear directorio de trabajo
WORKDIR /app

# Copiar solo los archivos necesarios desde la etapa de build
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules


# Exponer el puerto (ajusta según tu app)
EXPOSE 3000

# Comando para ejecutar la app
CMD ["node", "index.js"]